### PR TITLE
Support change this.state.pickerValue with props

### PR DESCRIPTION
**Pull request by bakso**
Support change this.state.pickerValue with props.value

### CODE REVIEW

**Comment by warmhug** [comment]
Sorry, the fix_3.0.5_ts_error branch is out of date.

**Comment by bakso** [comment]
Which 3.0.x branch I should merge to ?

**Comment by warmhug** [comment]
Maybe it is not necessary

**Comment by paranoidjk** [comment]
close this, since it had been fixed in rmc-picker

https://github.com/react-component/m-picker/blob/master/src/PopupMixin.tsx#L28

**Pull request closed without merging**
